language: node_js
sudo: true
dist: trusty
node_js:
    - 'stable'

script:
  - npm test

branches:
    only:
        - master
env:
    global:
        - CHROME_BIN=/usr/bin/google-chrome
        - DISPLAY=:99.0
cache:
  directories:
     - node_modules
notifications:
email: false
after_script:
  - cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
