language: node_js
sudo: true
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
node_js:
    - 'stable'
cache:
  directories:
    - node_modules
# allow headful tests
before_install:
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
  # Launch XVFB
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - npm test

branches:
    only:
        - master
env:
    global:
        - CHROME_BIN=/usr/bin/google-chrome
        - DISPLAY=:99.0
cache:
  directories:
     - node_modules
notifications:
email: false
after_script:
  - cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
